services:
    werkint.social:
        class: Werkint\Bundle\SocialBundle\Social\Service
        arguments:
            - @werkint.webapp
            - %werkint_social%
    werkint.social.facebook:
        class: Werkint\Bundle\SocialBundle\Social\Facebook
        arguments:
            - %werkint_social%
    werkint.social.vkontakte:
        class: Werkint\Bundle\SocialBundle\Social\Vkontakte
        arguments:
            - %werkint_social%