services:
    werkint.social:
        class: Werkint\Bundle\SocialBundle\Service\Social
        arguments:
            - @werkint.webapp
            - %werkint_social%
    werkint.social.provider.facebookprovider:
        class: Werkint\Bundle\SocialBundle\Service\Provider\FacebookProvider
        arguments:
            - %werkint_social%
    werkint.social.provider.vkontakteprovider:
        class: Werkint\Bundle\SocialBundle\Service\Provider\VkontakteProvider
        arguments:
            - %werkint_social%